# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d0d2d4a26f6b1d1c4b6afa0607a885a9"
name = "Organise Americano"
application_url = "https://americano-tournament-app-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_legal_policies,write_locations,read_locations,read_online_store_pages,write_online_store_pages,read_product_feeds,write_product_feeds,read_product_listings,write_product_listings,read_products,write_products,read_content,write_content,read_translations,write_translations"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://americano-tournament-app-production.up.railway.app/auth/callback",
  "https://americano-tournament-app-production.up.railway.app/auth/shopify/callback",
  "https://americano-tournament-app-production.up.railway.app/api/auth/callback"
]
